version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: "cargo"
    directory: "/"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: direct
    schedule:
      interval: monthly
