[package]
name = "typed-handlebars"
description = "Compile-time checked Handlebars templates for Rust"
documentation = "https://docs.rs/typed-handlebars"
readme = "../README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
typed-handlebars-macros = { path = "../typed-handlebars-macros", version = "0.2.0" }

[dev-dependencies]
trybuild = "1.0"

[package.metadata.docs.rs]
all-features = true
